/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InequalitiesRouteImport } from './routes/inequalities'
import { Route as LiteralsRouteImport } from './routes/literals'
import { Route as StepboardRouteImport } from './routes/stepboard'
import { Route as SystemsEliminationRouteImport } from './routes/systems-elimination'
import { Route as SystemsSubstitutionRouteImport } from './routes/systems-substitution'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InequalitiesRoute = InequalitiesRouteImport.update({
  id: '/inequalities',
  path: '/inequalities',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteralsRoute = LiteralsRouteImport.update({
  id: '/literals',
  path: '/literals',
  getParentRoute: () => rootRouteImport,
} as any)
const StepboardRoute = StepboardRouteImport.update({
  id: '/stepboard',
  path: '/stepboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsEliminationRoute = SystemsEliminationRouteImport.update({
  id: '/systems-elimination',
  path: '/systems-elimination',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSubstitutionRoute = SystemsSubstitutionRouteImport.update({
  id: '/systems-substitution',
  path: '/systems-substitution',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inequalities': typeof InequalitiesRoute
  '/literals': typeof LiteralsRoute
  '/stepboard': typeof StepboardRoute
  '/systems-elimination': typeof SystemsEliminationRoute
  '/systems-substitution': typeof SystemsSubstitutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inequalities': typeof InequalitiesRoute
  '/literals': typeof LiteralsRoute
  '/stepboard': typeof StepboardRoute
  '/systems-elimination': typeof SystemsEliminationRoute
  '/systems-substitution': typeof SystemsSubstitutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inequalities': typeof InequalitiesRoute
  '/literals': typeof LiteralsRoute
  '/stepboard': typeof StepboardRoute
  '/systems-elimination': typeof SystemsEliminationRoute
  '/systems-substitution': typeof SystemsSubstitutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inequalities'
    | '/literals'
    | '/stepboard'
    | '/systems-elimination'
    | '/systems-substitution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inequalities'
    | '/literals'
    | '/stepboard'
    | '/systems-elimination'
    | '/systems-substitution'
  id:
    | '__root__'
    | '/'
    | '/inequalities'
    | '/literals'
    | '/stepboard'
    | '/systems-elimination'
    | '/systems-substitution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InequalitiesRoute: typeof InequalitiesRoute
  LiteralsRoute: typeof LiteralsRoute
  StepboardRoute: typeof StepboardRoute
  SystemsEliminationRoute: typeof SystemsEliminationRoute
  SystemsSubstitutionRoute: typeof SystemsSubstitutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inequalities': {
      id: '/inequalities'
      path: '/inequalities'
      fullPath: '/inequalities'
      preLoaderRoute: typeof InequalitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literals': {
      id: '/literals'
      path: '/literals'
      fullPath: '/literals'
      preLoaderRoute: typeof LiteralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stepboard': {
      id: '/stepboard'
      path: '/stepboard'
      fullPath: '/stepboard'
      preLoaderRoute: typeof StepboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems-elimination': {
      id: '/systems-elimination'
      path: '/systems-elimination'
      fullPath: '/systems-elimination'
      preLoaderRoute: typeof SystemsEliminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems-substitution': {
      id: '/systems-substitution'
      path: '/systems-substitution'
      fullPath: '/systems-substitution'
      preLoaderRoute: typeof SystemsSubstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InequalitiesRoute: InequalitiesRoute,
  LiteralsRoute: LiteralsRoute,
  StepboardRoute: StepboardRoute,
  SystemsEliminationRoute: SystemsEliminationRoute,
  SystemsSubstitutionRoute: SystemsSubstitutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
